=== Ogierumua/csym019_assignment_2023/Task1/src/courseschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "Images": {
          "type": "string"
        },
        "SubjectArea": {
          "type": "string"
        },
        "CourseName": {
          "type": "string"
        },
        "CourseDetails": {
          "type": "string"
        },
        "Level": {
          "type": "string"
        },
        "EntryRequirement": {
          "type": "string"
        },
        "FeesandFunding": {
          "type": "string"
        },
        "KeyFacts": {
          "type": "string"
        }
      },
      "required": [
        "Images",
        "SubjectArea",
        "CourseName",
        "CourseDetails",
        "Level",
        "EntryRequirement",
        "FeesandFunding",
        "KeyFacts"
      ]
    }
  }

=== Ogierumua/csym019_assignment_2023/webserver/src/course.json
[
    {
        "Images":"coursesImages/computersci.png" ,
        "SubjectArea":"Computing",
        "CourseName":"Computer Science (Bsc)",
        "CourseDetails":   "Year 1, During the first year of your  computer science degree, you will study common computer science modules such as Computer Systems, Software Engineering Fundamentals, Mathematics,  Computer Science, Web Development, Problem Solving & Programming. These will help you build a foundation base around more advanced topics  subsequent years ",
        "Level":"Undergraduate",
        "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
        "FeesandFunding": "International Full Time £17,250",
        "KeyFacts": "Duration: 1Year, Location: Waterside Campus"
     },

     {
        "Images":"coursesImages/humanities.png",
        "SubjectArea":"Humanities",
        "CourseName":"English (BA)",
        "CourseDetails":   "The modules on this English BA (Hons) course are organised into distinctive strands that allow students the chance to develop their knowledge from year to year and apply skills they have learned across different stages. For example, in a strand called Rethinking Identities, we raise the question of which authors are taught right from the start in a module called Decolonising the Bookshelf, with a particular focus on race and ethnicity. But these same ideas return in the second year of the BA English degree with Representing Class: Stories and Conflict and in the third year with Bodies and Performances: Sex and Gender, and in this way students are able, if they choose, to fully develop their understanding of literary expression, representation and recognition across a broad range of literary texts",
        "Level":"Undergraduate",
        "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
        "FeesandFunding": "International Full Time £17,250",
        "KeyFacts": "Duration: 1Year, Location: Waterside Campus"
     },

     {
        "Images":"coursesImages/sportssci.png",
        "SubjectArea":"Sport Science",
        "CourseName":"Sport Coaching (Bsc)",
        "CourseDetails":"The coaching process,developing your own coaching philosophy, coaching styles, effective coaching approaches, long term athlete development and comprehensive planning analysis are at the core of our Sport Coaching degree. As well as performance analysis and work placement modules.",
        "Level":"Undergraduate",
        "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
        "FeesandFunding": "International Full Time £17,250",
        "KeyFacts": "Duration: 1Year, Location: Waterside Campus"
     },

     {
        "Images":"coursesImages/musicandart.png",
        "SubjectArea":"Music and Art",
        "CourseName":"Acting (BA)",
        "CourseDetails":"The coaching process, pedagogy, developing your own coaching philosophy, coaching styles, effective coaching approaches, long term athlete development and comprehensive planning/needs analysis are at the core of our Sport Coaching degree. As well as performance analysis, coaching theory and work placement modules.",
        "Level":"Undergraduate",
        "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
        "FeesandFunding": "International Full Time £17,250",
        "KeyFacts": "Duration: 1Year, Location: Waterside Campus, Start Time: September & January"
     },

     {
        "Images":"coursesImages/media.png",
        "SubjectArea":"Media and Journalism",
        "CourseName":"Film and Screen Study (BA)",
        "CourseDetails":"The coaching process, pedagogy, developing your own coaching philosophy, coaching styles, effective coaching approaches, long term athlete development and comprehensive planning/needs analysis are at the core of our Sport Coaching degree. As well as performance analysis, coaching theory and work placement modules.",
        "Level":"Undergraduate",
        "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
        "FeesandFunding": "International Full Time £17,250",
        "KeyFacts": "Duration: 1Year, Location: Waterside Campus, Start Time: September & January"
     },

     {
      "Images":"coursesImages/Accounting.png",
      "SubjectArea":"Accounting and Finance",
      "CourseName":"Acounting and Finance (MSC)",
      "CourseDetails":"The coaching process, pedagogy, developing your own coaching philosophy, coaching styles, effective coaching approaches, long term athlete development and comprehensive planning/needs analysis are at the core of our Sport Coaching degree. As well as performance analysis, coaching theory and work placement modules.",
      "Level":"Postgraduate",
      "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
      "FeesandFunding": "International Full Time £17,250",
      "KeyFacts": "Duration: 1Year, Location: Waterside Campus, Start Time: September & January"
   },
   {
      "Images":"coursesImages/digitalmkt.png",
      "SubjectArea":"Avertising and Marketing",
      "CourseName":"Digital Marketing (MSC)",
      "CourseDetails":"This course explores the exciting and dynamic world of digital marketing. You will investigate the debates around the Virtual Reality, the Metaverse, Artificial Intelligence, Digital Transformation and Digital skills that are framing the world around us.Accredited by the Digital Marketing Institute (DMI), this Masters will also allow you to be certified as a Certified Digital Marketing Professional. Membership of the DMI is Included in the course fee and gives you access to a wealth of study materials and rich content via the DMI student online portal.",
      "Level":"Postgraduate",
      "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
      "FeesandFunding": "International Full Time £17,250",
      "KeyFacts": "Duration: 1Year, Location: Waterside Campus, Start Time: September & January"
   },
   {
      "Images":"coursesImages/molecular.png",
      "SubjectArea":"Biological Science",
      "CourseName":"Molecular Bioscience(MSC)",
      "CourseDetails":"The Molecular Bioscience MSc programme supports you to develop your knowledge and understanding of key aspects of your chosen pathway and is aimed at individuals that have a prior knowledge of, or keen interest in, Molecular Medicine or Genetics and Genomics.",
      "Level":"Postgraduate",
      "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
      "FeesandFunding": "International Full Time £17,250",
      "KeyFacts": "Duration: 1Year, Location: Waterside Campus, Start Time: September & January"
   },
   {
      "Images":"coursesImages/lift.png",
      "SubjectArea":"Engineering",
      "CourseName":"Lift Engineering (MSC)",
      "CourseDetails": "On this lift engineer course, we aim to provide you with a detailed, academic study of lift engineering and related management issues, together with a higher level qualification for persons employed in lift engineering and allied industries.",
      "Level":"Postgraduate",
      "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
      "FeesandFunding": "International Full Time £17,250",
      "KeyFacts": "Duration: 1Year, Location: Waterside Campus"
   },
   {
      "Images":"coursesImages/leather.png",
      "SubjectArea":"Leather and Fashion",
      "CourseName":"Leather Technology (MSC)",
      "CourseDetails": "Our unique Leather Technology (Professional) MSc will give you the opportunity to enhance your technical skills. We encourage you to develop intellectual creativity and we will provide you with the skills you need to research advanced technologies",
      "Level":"Postgraduate",
      "EntryRequirement":"Applicants must be 18 years old by the 2nd month of commencing pre-registration nursing programmes and all applicants must have 10 years of consecutive education",
      "FeesandFunding": "International Full Time £17,250",
      "KeyFacts": "Duration: 1Year, Location: Waterside Campus"
   }






]
